config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :members
  has_many :users, through: :members
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      result = []
      result.push last_message.body if last_message.body?
      result.push ActionController::Base.helpers.image_tag(last_message.image.url(:thumb)) if last_message.image.present?
      return result
    else
      ['まだメッセージはありません。']
    end
  end

end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  mount_uploader :image, MessageImageUploader
  validates :body, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :members
  has_many :groups, through: :members
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @chat_messages = Message.where("id > #{params[:id]}").where(group_id: params[:group_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @chat_messages = @group.messages.includes(:user)
    @chat_message = Message.new
  end

  def create
    @chat_message = @group.messages.new(message_params)
    respond_to do |format|
      if @chat_message.save
        format.html { redirect_to group_messages_path, notice: 'メッセージが送信されました' }
        format.json
      else
        format.html {
          @chat_messages = @group.messages.includes(:user)
          flash.now[:alert] = 'メッセージを入力してください。'
          render :index
        }
        format.json
      end
    end
  end

  private
  def message_params
    parameter = params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE ?', "#{params[:search]}%").where.not(id: current_user)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = text_field :users, :search, placeholder: '追加したいユーザー名を入力してください', class: "chat-group-form__input", id: 'user-search-field'
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        %div{ class: "chat-group-user clearfix js-chat-member", id: "chat-group-user-#{current_user.id}" }
          = f.hidden_field :user_ids, multiple: true, value: current_user.id, id: ''
          %p.chat-group-user__name="#{current_user.name}"
        - group.users.each do |user|
          - next if user.id == current_user.id
          %div{ class: "chat-group-user clearfix js-chat-member", id: "chat-group-user-#{user.id}" }
            = f.hidden_field :user_ids, multiple: true, value: user.id, id: ''
            %p.chat-group-user__name="#{user.name}"
            .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn="削除"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrap
  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/flash'
    = yield

app/views/messages/_chat_message.html.haml
%div{ class: "chat-message-container", data: {id: "#{chat_message.id}"} }
  .chat-message__info
    %p.chat-message__username
      = chat_message.user.name
    %p.chat-message__date
      = chat_message.created_at.strftime("%Y/%m/%d(%a) %H:%M:%S")
  .chat-message__message
    %p=chat_message.body
    - unless chat_message.image.file.nil?
      = image_tag chat_message.image.url

app/views/messages/index.html.haml
.wrap
  = render 'shared/side_bar'
  .contents
    .contents__head.contents__head--fit
      .current-group--left
        %p.current-group__name=@group.name
        %p.current-group__members
          = "Member : #{@group.users.map {|user| user.name}.join(' ')}"
      .current-group--right
        =link_to "Edit", edit_group_path(@group), class: "current-group__btn current-group__btn--fit"
    .contents__chat-messages
      = render partial: 'chat_message', collection: @chat_messages
    .contents__foot
      = form_for [@group, @chat_message], html: {class: "chat-form"} do |f|
        .chat-form__upload
          = f.text_field :body, class: "chat-form__message", placeholder: "type a message"
          = f.label :image, '', class: 'chat-form__upload--label' do
            = fa_icon 'image', class: 'chat-form__upload--icon'
            = f.file_field :image, class: "chat-form__upload--hidden"
        = f.submit "Send", class: "chat-form__btn chat-form__btn--fit"

app/views/shared/_chat_group.html.haml
.chat-group
  = link_to group_messages_path(chat_group) do
    .chat-group__name
      = chat_group.name
    .chat-group__info
      - chat_group.show_last_message.each do |c|
        = c

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  %div{class: "flash-msg flash-msg--#{key}"}
    = value

app/views/shared/_side_bar.html.haml
.sidebar
  .sidebar__head
    .chat-user
      %p.chat-user__name<>
        = current_user.name
      %ul.chat-user__items
        %li.chat-user__item
          =link_to new_group_path, class: "chat-user__btn" do
            = fa_icon 'edit', class: "chat_user__btn--icon"
        %li.chat-user__item
          =link_to edit_user_path(current_user.id), class: "chat-user__btn" do
            = fa_icon 'cog', class: "chat_user__btn--icon"
  .sidebar__chat-groups
    = render partial: 'shared/chat_group', collection: current_user.groups

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, class: 'btn', method: :delete
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'